version: '3'

services:
  app:
    image: haigerhana/fermon-server
    ports:
      - "4000:4000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./data/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
