name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts
    

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fermon-server:latest

    - name: connect and pull
      run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker compose pull && docker compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh

    # - name: SSH and deploy to VPS
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.VPS_HOST }}
    #     username: ${{ secrets.VPS_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       docker-compose -f ./docker-compose.yml pull
    #       docker-compose -f ./docker-compose.yml up -d
