name: CI/CD Fermon Server

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fermon-server:latest
  
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: SSH and deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fermon-server:latest

          if docker ps -a --format '{{.Names}}' | grep -q '^fermon-server$'; then
            docker stop fermon-server
            docker rm fermon-server
          fi

          docker system prune -f
          docker run --name fermon-server -dit \
            -p 4455:4455 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/fermon-server:latest
